/**
 * Detects when a shell command failure was likely caused by the user
 * typing natural language instead of a real shell command.
 */

/**
 * Shell error patterns that strongly suggest natural language input.
 * These are parse/syntax errors that occur when the shell tries to
 * interpret English sentences as code.
 */
const ERROR_PATTERNS = [
  // zsh/bash parse errors
  /parse error/i,
  /syntax error/i,
  /unexpected token/i,
  /unexpected end of file/i,
  // command not found for subsequent words (the first word was valid but rest isn't shell)
  /command not found/i,
  // common errors from real commands receiving natural language args
  /no such file or directory/i,
  /invalid option/i,
  /unrecognized option/i,
  /illegal option/i,
  /unknown option/i,
  // make
  /no rule to make target/i,
  // find
  /unknown primary or operator/i,
  /missing argument to/i,
  // grep
  /invalid regular expression/i,
  // git
  /is not a git command/i,
  // subcommand-based tools (go, cargo, docker, npm, kubectl, etc.)
  /unknown command/i,
  /no such command/i,
]

/**
 * Words that are common in natural language but unusual as the second
 * token of a real shell command. Used as a signal that the input is
 * probably a sentence, not a command.
 *
 * Kept in sync with lacyshell lib/core/constants.sh LACY_NL_MARKERS.
 */
const NATURAL_LANGUAGE_WORDS = new Set([
  // articles/determiners
  "a",
  "an",
  "the",
  "this",
  "that",
  "these",
  "those",
  "my",
  "our",
  "your",
  "its",
  "their",
  "his",
  "her",
  // pronouns
  "i",
  "we",
  "you",
  "it",
  "they",
  "me",
  "us",
  "him",
  "her",
  "them",
  "myself",
  "yourself",
  "itself",
  "ourselves",
  "themselves",
  // prepositions
  "to",
  "of",
  "about",
  "with",
  "from",
  "for",
  "into",
  "through",
  "between",
  "after",
  "before",
  "during",
  "without",
  "within",
  "against",
  "above",
  "below",
  "under",
  "upon",
  "across",
  "toward",
  "towards",
  "beside",
  "besides",
  "beyond",
  "except",
  "inside",
  "outside",
  "behind",
  "near",
  "among",
  "along",
  "around",
  // conjunctions
  "and",
  "but",
  "or",
  "so",
  "because",
  "since",
  "although",
  "though",
  "unless",
  "while",
  "whereas",
  "whether",
  "however",
  "therefore",
  "moreover",
  "furthermore",
  "nevertheless",
  "otherwise",
  "instead",
  // common verbs (when second word)
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "having",
  "can",
  "could",
  "would",
  "should",
  "will",
  "shall",
  "may",
  "might",
  "must",
  "need",
  "want",
  "know",
  "think",
  "believe",
  "understand",
  "remember",
  "forget",
  "seem",
  "appear",
  "look",
  "feel",
  "sound",
  "mean",
  "try",
  "keep",
  "let",
  "begin",
  "start",
  "stop",
  "continue",
  "happen",
  "work",
  "run",
  "give",
  "take",
  "bring",
  "send",
  "put",
  "get",
  "got",
  "went",
  "going",
  "done",
  "doing",
  "made",
  "making",
  // adverbs
  "not",
  "already",
  "also",
  "just",
  "still",
  "even",
  "really",
  "actually",
  "probably",
  "maybe",
  "perhaps",
  "always",
  "never",
  "sometimes",
  "often",
  "usually",
  "only",
  "very",
  "too",
  "enough",
  "quite",
  "rather",
  "pretty",
  "almost",
  "nearly",
  "completely",
  "entirely",
  "definitely",
  "certainly",
  "obviously",
  "clearly",
  "honestly",
  "basically",
  "literally",
  "seriously",
  "hopefully",
  "unfortunately",
  "apparently",
  "absolutely",
  "simply",
  "merely",
  "exactly",
  "roughly",
  // question words
  "how",
  "what",
  "when",
  "where",
  "why",
  "who",
  "which",
  "whom",
  "whose",
  // other common sentence words
  "if",
  "there",
  "here",
  "all",
  "any",
  "some",
  "every",
  "no",
  "each",
  "does",
  "do",
  "did",
  "sure",
  "out",
  "up",
  "down",
  "ahead",
  "back",
  "over",
  "away",
  "off",
  "on",
  "now",
  "then",
  "again",
  "once",
  "twice",
  "first",
  "last",
  "next",
  "new",
  "old",
  "same",
  "other",
  "another",
  "both",
  "either",
  "neither",
  "much",
  "many",
  "more",
  "most",
  "less",
  "least",
  "few",
  "several",
  "own",
  "such",
  "whole",
  "entire",
  // conversational/reactions
  "please",
  "thanks",
  "thank",
  "sorry",
  "yes",
  "yeah",
  "yep",
  "ok",
  "okay",
  "alright",
  "right",
  "correct",
  "wrong",
  "perfect",
  "great",
  "good",
  "nice",
  "cool",
  "awesome",
  "amazing",
  "wonderful",
  "excellent",
  "fantastic",
  "brilliant",
  "fine",
  "terrible",
  "horrible",
  "awful",
  "bad",
  "worse",
  "worst",
  "better",
  "best",
  // indefinite pronouns
  "anyone",
  "someone",
  "everyone",
  "anything",
  "something",
  "everything",
  "nobody",
  "nothing",
  "nowhere",
  "wherever",
  "whatever",
  "whoever",
  "whenever",
  "however",
  // common nouns used in conversation
  "way",
  "thing",
  "things",
  "stuff",
  "part",
  "place",
  "point",
  "fact",
  "issue",
  "problem",
  "question",
  "answer",
  "idea",
  "reason",
  "example",
  "change",
  "error",
  "bug",
  "fix",
  "feature",
  "code",
  "file",
  "files",
  "repo",
  "project",
  "app",
  "test",
  "tests",
])

/**
 * Minimum word count for the input to be considered potentially natural language.
 * Single-word inputs are usually real commands (`ls`, `git`), but two-word inputs
 * like "go ahead" or "make sure" are often natural language when the command errors.
 */
const MIN_WORD_COUNT = 2

/**
 * Detect if a failed shell command was likely natural language.
 *
 * Returns true if natural language is detected, undefined otherwise.
 */
export function detectNaturalLanguage(input: string, output: string, exitCode: number | null): true | undefined {
  // Only check failed commands
  if (exitCode === 0 || exitCode === null) return undefined

  const trimmed = input.trim()
  const words = trimmed.split(/\s+/)

  // Very short inputs are probably real commands
  if (words.length < MIN_WORD_COUNT) return undefined

  // Check if the output matches known error patterns
  const hasErrorPattern = ERROR_PATTERNS.some((pattern) => pattern.test(output))
  if (!hasErrorPattern) return undefined

  // Check if the second word looks like natural language
  const second = words[1]?.toLowerCase()
  if (second && NATURAL_LANGUAGE_WORDS.has(second)) return true

  // Even without a natural language second word, if we have many words
  // and a parse/syntax error, it's likely natural language
  if (words.length >= 4 && /parse error|syntax error|unexpected token/i.test(output)) return true

  return undefined
}
