package core

// Centralized key strings for global shortcuts
const (
	KeyCtrlC      = "ctrl+c"
	KeyCtrlD      = "ctrl+d"
	KeyCtrlG      = "ctrl+g"
	KeyCtrlE      = "ctrl+e"
	KeyCtrlF      = "ctrl+f"
	KeyCtrlO      = "ctrl+o"
	KeyCtrlR      = "ctrl+r"
	KeyCtrlP      = "ctrl+p"
	KeyCtrlS      = "ctrl+s"
	KeyCtrlN      = "ctrl+n"
	KeyCtrlZ      = "ctrl+z"
	KeyCtrlSpace  = "ctrl+space"
	KeyShiftTab   = "shift+tab"
	KeyShiftUp    = "shift+up"
	KeyShiftDown  = "shift+down"
	KeyShiftLeft  = "shift+left"
	KeyShiftRight = "shift+right"
	KeyCtrlY      = "ctrl+y"
	KeyCtrlJ      = "ctrl+j"
	KeyCtrlK      = "ctrl+k"
	KeyCtrlA      = "ctrl+a"
	KeyTab        = "tab"
	KeyEsc        = "esc"
	KeyEnter      = "enter"
	KeyShiftEnter = "shift+enter"
	KeyUp         = "up"
	KeyDown       = "down"
	KeyLeft       = "left"
	KeyRight      = "right"
	KeyPageUp     = "pgup"
	KeyPageDown   = "pgdown"
	KeyHome       = "home"
	KeyEnd        = "end"
	KeySpace      = " "
	KeySlash      = "/"
	KeyB          = "b"
	KeyF          = "f"
	KeyU          = "u"
	KeyD          = "d"
	KeyG          = "g"
	KeyCapitalG   = "G"
	KeyR          = "r"
	KeyH          = "h"
	KeyJ          = "j"
	KeyK          = "k"
	KeyL          = "l"
	KeyCapitalH   = "H"
	KeyCapitalJ   = "J"
	KeyCapitalK   = "K"
	KeyCapitalL   = "L"
	KeyA          = "a"
	KeyCapitalA   = "A"
	KeyS          = "s"
	KeyCapitalS   = "S"
	KeyC          = "c"
	KeyCapitalC   = "C"
	KeyO          = "o"
	KeyY          = "y"
	KeyCapitalY   = "Y"
	KeyN          = "n"
	KeyCapitalN   = "N"
	KeyT          = "t"
	KeyCapitalT   = "T"
)

// Centralized help label strings for global shortcuts
const (
	HelpQuit        = "quit"
	HelpMore        = "more"
	HelpCommands    = "commands"
	HelpSessions    = "sessions"
	HelpNewSessions = "new sessions"
	HelpSuspend     = "suspend"
	HelpMode        = "mode"
	HelpAutoConfirm = "auto-confirm"
	HelpYolo        = "yolo"
)
